version: '3.6'

services:
  db:
     image: postgres
     networks:
       pizza_net:
         aliases:
           - db_server
  web:
    networks:
      - pizza_net
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  memcached:
    networks:
      pizza_net:
        aliases:
          - memcache_server
    image: sameersbn/memcached:latest
    ports:
      - "11211:11211"
    restart: always

networks:
  pizza_net: